version: '3.8'

services:
  g-a-node-1:
    build: .
    container_name: g-a-node-1
    environment:
      - GROUP_ID=A
      - NODE_ID=1
      - ALL_NODES=g-a-node-1:5001,g-a-node-2:5002,g-a-node-3:5003,g-b-node-1:6001,g-b-node-2:6002,g-b-node-3:6003
    networks:
      - distributed-system

  g-a-node-2:
    build: .
    container_name: g-a-node-2
    environment:
      - GROUP_ID=A
      - NODE_ID=2
      - ALL_NODES=g-a-node-1:5001,g-a-node-2:5002,g-a-node-3:5003,g-b-node-1:6001,g-b-node-2:6002,g-b-node-3:6003
    networks:
      - distributed-system

  g-a-node-3:
    build: .
    container_name: g-a-node-3
    environment:
      - GROUP_ID=A
      - NODE_ID=3
      - ALL_NODES=g-a-node-1:5001,g-a-node-2:5002,g-a-node-3:5003,g-b-node-1:6001,g-b-node-2:6002,g-b-node-3:6003
    networks:
      - distributed-system

  g-b-node-1:
    build: .
    container_name: g-b-node-1
    environment:
      - GROUP_ID=B
      - NODE_ID=1
      - ALL_NODES=g-a-node-1:5001,g-a-node-2:5002,g-a-node-3:5003,g-b-node-1:6001,g-b-node-2:6002,g-b-node-3:6003
    networks:
      - distributed-system

  g-b-node-2:
    build: .
    container_name: g-b-node-2
    environment:
      - GROUP_ID=B
      - NODE_ID=2
      - ALL_NODES=g-a-node-1:5001,g-a-node-2:5002,g-a-node-3:5003,g-b-node-1:6001,g-b-node-2:6002,g-b-node-3:6003
    networks:
      - distributed-system

  g-b-node-3:
    build: .
    container_name: g-b-node-3
    environment:
      - GROUP_ID=B
      - NODE_ID=3
      - ALL_NODES=g-a-node-1:5001,g-a-node-2:5002,g-a-node-3:5003,g-b-node-1:6001,g-b-node-2:6002,g-b-node-3:6003
    networks:
      - distributed-system

networks:
  distributed-system: