version: '3.8'

services:
  node-1:
    build: .
    container_name: node-1
    environment:
      - NODE_ID=1
      - PORT=5001
      - GRPC_PORT=6001
      - ALL_NODES=node-1:5001,node-2:5002,node-3:5003
      - ALL_GRPC_NODES=node-1:6001,node-2:6002,node-3:6003
    networks:
      - distributed-system

  node-2:
    build: .
    container_name: node-2
    environment:
      - NODE_ID=2
      - PORT=5002
      - GRPC_PORT=6002
      - ALL_NODES=node-1:5001,node-2:5002,node-3:5003
      - ALL_GRPC_NODES=node-1:6001,node-2:6002,node-3:6003
    networks:
      - distributed-system

  node-3:
    build: .
    container_name: node-3
    environment:
      - NODE_ID=3
      - PORT=5003
      - GRPC_PORT=6003
      - ALL_NODES=node-1:5001,node-2:5002,node-3:5003
      - ALL_GRPC_NODES=node-1:6001,node-2:6002,node-3:6003
    networks:
      - distributed-system

networks:
  distributed-system: